kodiak/evaluation.py
kodiak/test_evaluation.py

- add test to ensure that merging is disabled when whitelist is empty

Simplify whitelist and blacklist checks

---

CHANGELOG.md
kodiak/conftest.py
kodiak/evaluation.py
kodiak/queries.py
kodiak/test/fixtures/api/get_event/behind.json
kodiak/test_evaluation.py
kodiak/test_queries.py
poetry.lock
pyproject.toml

We want to ignore old `CHANGES_REQUESTED` reviews that are superseded by `APPROVED` reviews.
CHANGES
- add arrow to make dealing with datetimes easier
- fix bug in handling of reviews

Fix CHANGES_REQUESTED reviews

---

CHANGELOG.md
kodiak/conftest.py
kodiak/main.py
kodiak/queries.py
kodiak/test_evaluation.py
kodiak/test_main.py
kodiak/test_queries.py

Enabling `include_pr_number` with a non-default merge message option
will append the pr number to the commit message, like the Github UI.

Add support for include_pr_number configuration

---

kodiak/config.py
kodiak/test_config.py
kodiak/test_evaluation.py

app_id is configured as a string, so the configuration should be a
string as well.

fix: correct bad type for configuration of app_id

---

README.md
kodiak/config.py
kodiak/evaluation.py
kodiak/test/fixtures/config/v1-default.toml
kodiak/test/fixtures/config/v1-opposite.toml
kodiak/test_config.py
kodiak/test_evaluation.py

This will help fix the infinite loop that occurs from the WIP app. Since
that app sets the check-run to "in-progress" instead of "failed", kodiak
will wait forever for the check to finish if the PR is up for merging.
With blacklist_title_regex, we can simply set it to match the behavior
of the WIP app and mark the PR as not mergeable early on.

Add blacklist_title_regex. Rename blacklist to blacklist_labels.

---

README.md
kodiak/evaluation.py
kodiak/main.py
kodiak/queries.py
kodiak/test_evaluation.py
kodiak/test_main.py

Display information about merging process to users through a github check.
EXAMPLES

Show kodiak state information in Github CheckRun

---

.circleci/config.yml
README.md
kodiak/app_config.py
kodiak/main.py
poetry.lock
pyproject.toml

By storing events in a set we can cut down on processing pull requests
multiple times in short succession.
Previously, events for a pull request could be entered multiple times
into the redis queue. Now a pull request can only be in the queue once.
We're using `bzpopmin`, which is only supported by redis v5 or later. It
is also not supported by asyncio_redis yet, so we need to make a change
there.

ref: reduce unnecessary pull request processing

---

kodiak/main.py
kodiak/test_main.py

We now will only automatically delete branches if delete_branch_on_merge
is set.

add(conf): respect delete_branch_on_merge configuration option

---

kodiak/main.py

- support updating status of PRs when merge is in progress
- create tasks for incoming webhook events
- create _one_ task per repo merge queue

ref: improve backend architecture

---

kodiak/evaluation.py
kodiak/test_evaluation.py

Our previous logic would try to merge when a PR had the draft state, which is incorrect. Now we correctly abort.

fix(evaluation): handle draft state

---

kodiak/evaluation.py
kodiak/pull_request.py
kodiak/queries.py

CHANGES
- add message when PR is good to merge
- reduce some duplicated logic in mergeability for set_status
BEFORE
AFTER

ref(notifications): improve github check messages for PR status

---

kodiak/pull_request.py

MissingAppID exceptions are raised when we have multiple instances of kodiak running and only one is allowed to run based on a Github app ID specified in the configuration. We generally want to provide no response if we disabled via a mismatched app ID.

fix(notifications): ignore MissingAppID exceptions in status messages

---

kodiak/config.py
kodiak/evaluation.py
kodiak/test/fixtures/config/v1-default.toml
kodiak/test/fixtures/config/v1-opposite.toml
kodiak/test_config.py
kodiak/test_evaluation.py

If `require_automerge_label` is set to false, Kodiak will not require `automerge_label` to enqueue a PR for merge.
Fixes #81

add: require_automerge_label config

---

kodiak/pull_request.py

Kodiak and Github appear to have different opinions on what a mergeable
PR is in some cases. This change adds some logging to help us discover
why.
Related #83

hotfix: add logging to help debug errors

---

kodiak/pull_request.py
kodiak/test_pull_request.py

Previously, before commenting on a PR with an `automerge` label & a merge-conflict, Kodiak would remove the `automerge` label to ensure we don't post a comment twice.
After adding the feature to not require `automerge` labels this assumption no longer holds true.
Ideally we would just check to see if there is an `automerge` label before posting, but just not notifying is easier in the mean time and doesn't use up any more of our rate limited api requests.

fix: bug w/ notifying on merge conflict & not required labels

---

kodiak/pull_request.py

We just had the `automerge` as in the body of the comment instead of the
user's actually configured automerge label.

fix: untemplated notify-on-conflict comment

---

kodiak/conftest.py
kodiak/evaluation.py
kodiak/test_evaluation.py

If requiresCommitSignatures is enabled in branch protections, kodiak cannot function because it cannot create a signed commit to merge the PR. This appears to be a limitation of the Github API.
TODO in future PR
- document requiresCommitSignatures limitation in README
Fixes #89

hotfix: warn about requiresCommitSignatures branch protection

---

README.md

We've never tested Kodiak with GitHub's required-signed-commits feature
and it turns out that GitHub's API prevents Kodiak from creating signed
commits -- aka, Kodiak doesn't work when this feature is enabled.

update(readme): warn about usage with signed commits not being supported

---

kodiak/queue.py

fix: template of update branch failure

---

README.md

Closing issue keywords do not work as documented in the Github docs: https://help.github.com/en/articles/closing-issues-using-keywords
It appears that Github doesn't handle bot users merging PRs that close issues via keywords. The related issues stay open after the PR is merged.

doc: closing issue keywords don't work with bot users

---

README.md

Some of these known issues are outdated. We also need to update our permissions to support [closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords).
Related: #122

doc: update known issues and permissions

---

kodiak/conftest.py
kodiak/messages.py
kodiak/pull_request.py
kodiak/queries.py
kodiak/test/fixtures/api/get_event/behind.json
kodiak/test_evaluation.py
kodiak/test_pull_request.py
kodiak/test_queries.py

Forks cannot be updated through the github API. This change provides a warning in this case. Kodiak can still merge the PR, just not update.
Related #104

add: warning about limitations of updating forks

---

kodiak/evaluation.py
kodiak/test_evaluation.py

Kodiak will merge PRs even if it doesn't know why it's blocked. This should cover the case of CODEOWNERS while a fix is built.

add: nicer error message for unknown block reason

---

README.md
kodiak/config.py
kodiak/evaluation.py
kodiak/test/fixtures/config/config-schema.json
kodiak/test/fixtures/config/v1-default.toml
kodiak/test/fixtures/config/v1-opposite.1.toml
kodiak/test/fixtures/config/v1-opposite.2.toml
kodiak/test_config.py
kodiak/test_evaluation.py

Sometimes a check will never succeed and will always stay in a pending state. We should be able to configure these checks so that kodiak doesn't wait infinitely while these checks stay in the pending state.
Fixes #118

add: config to ignore select pending status checks

---

.dockerignore
Dockerfile

Before we were installing deps after copying all of the code from the
repo into the container.
This breaks caching anytime the code changes.
Now the cache only breaks when either of the pyproject.toml and poetry.lock files change.

fix: docker caching

---

README.md
kodiak/config.py
kodiak/queue.py
kodiak/test/fixtures/config/config-schema.json
kodiak/test/fixtures/config/v1-default.toml
kodiak/test/fixtures/config/v1-opposite.1.toml
kodiak/test/fixtures/config/v1-opposite.2.toml
kodiak/test_config.py
kodiak/test_queue.py

This change enables us to update PRs immediately when their target branches update, instead of waiting until the PR is up for merge.
CHANGES
- add configuration `merge.update_branch_immediately`
- fix regression from #158 (this was never deployed, but we weren't awaiting a function)
Fixes #120

enable updating branches immediately

---

README.md

Kodiak does not support using the deprecated Travis-CI commit status updates for branch protection. Instead, users should upgrade to the newer GitHub Checks based solution.
Related #163, #166

doc: deprecated TravisCI commit status support

---

README.md

block_on_reviews_requested is fundamentally broken and cannot be fixed. This change documents this in the README.
closes #153

doc: block_on_reviews_requested problems

---

kodiak/config.py
kodiak/queue.py
kodiak/test/fixtures/config/config-schema.json
kodiak/test/fixtures/config/v1-default.toml
kodiak/test/fixtures/config/v1-opposite.1.toml
kodiak/test/fixtures/config/v1-opposite.2.toml
kodiak/test_config.py
kodiak/test_queue.py

In our workflow we need the ability to update a PR without merging it. This is because Kodiak does not support signed commits and as such we would like to keep our branches up to date once they are mergeable but wait to be manual merged. 
I think you were really close to this feature already. 
The first thing is your `update_pr_immediately_if_configured` already nicely waits for the PR to mergeable before it starts updating:
`update_pr_immediately_if_configured` only triggers if two things are true:
1) `update_branch_immediately` flag is `true` 
2) `m_res == MergeabilityResponse.NEEDS_UPDATE`
`1)` will protect this function from running for individuals who do not want this option. And `2)` actually already waits for the "smart updating" cycle because `MergeabilityResponse` prioritizes …

Add ability to do smart updating without merging 

---

kodiak/evaluation.py
kodiak/test_evaluation.py

This is blocked until I can find all the possible status checks that map to `continuous-integration/travis-ci`. I've opened an issue with GitHub, so hopefully they will have information.
fixes #163

fix: travis-ci check compression

---

kodiak/app_config.py

Docker's env file support is broken and doesn't support multi-line configuration variables. The private key needs to be passed via the -e flag.
With base64 encoding we can convert the key file to base64 and pass the encode version in a single line of the env file.

add: support for configuring PRIVATE_KEY via base64

---

kodiak/queries.py
kodiak/throttle.py
poetry.lock
pyproject.toml

The throttle package we were using was short and sweet but we couldn't
stick logging into it. Now we vendor it and add a logging option.
Hopefully this will make it more obvious when an installation reaches
their rate limit.

add: logging for throttle & vendor throttle pkg

---

kodiak/queries.py

This log was causing a lot of errors being reported to sentry.

fix: missing config log to be info

---

kodiak/pull_request.py

Logging this error was sending a lot of events to Sentry. The actual
issue is handled properly by Kodiak, so an `info` log is fine.

ref(logging): replace noisy error long with info log

---

kodiak/messages.py
kodiak/pull_request.py
kodiak/queries.py
kodiak/test_pull_request.py

Use pull request update-branch api instead of merge api to update branches. This new api allows us to update branches of forks, which wasn't possible with the merges api because of GitHub permissions.
fixes #104

enable updating forks

---

.kodiak.toml

`merge.block_on_reviews_requested` is deprecated and doesn't work well, so we shouldn't use it.

tools(kodiak): remove deprecated kodiak setting

---

kodiak/evaluation.py
kodiak/test_evaluation.py
poetry.lock
pyproject.toml

By throwing user provided regex into Python's regex module we ran the
risk of a ReDos, or more likely a blockage in the asyncio event loop.
This PR switches the logic to use `rure` which is a Python wrapper around
Rust's regex library.
rel: https://github.com/davidblewett/rure-python
rel: https://crates.io/crates/regex

ref: regex based blacklist to use linear matching

---

kodiak/logging.py
kodiak/main.py
kodiak/pull_request.py
kodiak/queries.py
kodiak/queue.py

CHANGES
- add logging processor to add detail to logs that have a requests Response object. Passing log.info("my message", res=Response()) gets rendered as Response<400> with no other information. Now we have more relevent information like response body, status code, request url and body.
- try to cut down on noisy logging where possible. We're going to get 500 errors from GitHub occasionally, so we can expect to get errors.

fix: logging to be less noisy and provide more info

---

kodiak/pull_request.py
kodiak/queue.py

We ended up deleting a lot of logging statements with the refactor. I think this change brings us to parity.
Also, you can't pass an arg "event" to logging statements because the first argument is called event. I found this issue by testing the app locally.

add: detail to logging

---

kodiak/logging.py
kodiak/test_logging.py

- fix issue where url was being used in place of method
- use ._content instead of .text because ._content won't raise an exception

fix: requests structlog processor to be more robust

---

kodiak/evaluation.py
kodiak/test_evaluation.py

This change adds a status message to updates triggered by `update.always` and adds a reason why the branch was update to the summary page.
I think we could probably make better use of the summary page for checks in the future to give more information about why Kodiak did something..

add: better status messages for updating branch

---

kodiak/evaluation.py
kodiak/queries.py
kodiak/test/fixtures/api/get_event/behind.json
kodiak/test_evaluation.py
kodiak/test_queries.py

Merge conflicts are not the same as rebase merge conflicts. It's possible for a PR to be mergeable for one method (like merge or squash) but for rebase to have it's own conflict. Now we check the canBeRebased property on pull requests to determine if there is a rebase merge conflict. We only check when the configured merge method is rebase.
fixes #222

fix: handling of rebase merge conflicts

---

kodiak/config.py
kodiak/evaluation.py
kodiak/test/fixtures/config/config-schema.json
kodiak/test_evaluation.py

merge.optimistic_merge is the default behavior of Kodiak at the moment. This change allows users to turn off this behavior of queuing a PR for merge while its status checks are still pending.

add: merge.optimistic_merge configuration

---

kodiak/evaluation.py
kodiak/test_evaluation.py

After testing, it appears that merge commits are supported when using requiresCommitSignatures (aka "Require signed commits" branch protection). This change updates the requiresCommitSignatures to only warn when rebase or squash merges are configured with requiresCommitSignatures.
related #89

remove commitSignatures warning for merge commits

---

kodiak/queries.py
kodiak/test/fixtures/api/get_event/behind.json
kodiak/test_queries.py

The collaborators API we use to check permissions on GitHub users does not work with bots, so we were getting API errors when a bot reviewed a PR. This change adds support for bot reviews.
If a bot reviews a PR, it means they have write access to a PR, so their review "counts" as a review of a user with write access to a repository.

add support for bot reviews

---

docs/README.md
docs/core/Footer.js
docs/docs/self-hosting.md
docs/pages/en/help.js
docs/pages/en/index.js
docs/static/css/custom.css

We had a decent number of broken links that I hopefully fixed.
Also fixed some issues with the `<pre>` tag for the config file on the
landing page overflowing and causing the page to scroll horizontally on
mobile.
Additionally the project name in the nav was hiding on mobile.

fix(docs): mobile CSS & broken links

---

docs/README.md
docs/siteConfig.js

docusaurus has an easy integration with https://community.algolia.com/docsearch/
Now there are two `env vars` required for build:
`AGOLIA_API_KEY` and `AGOLIA_INDEX_NAME`
note these env vars aren't secret as they are included in the build
artifacts.
Also updated the env vars in the netlify config section

add(docs): agolia doc search

---

README.md
docs/core/Footer.js
docs/docs/config-reference.md
docs/netlify.toml
docs/sidebars.json

Detailed setup doesn't actually provide much setup information but it does provide a config reference so that seems like a better name
Setup redirects using Netlify's config file https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file

ref(docs): rename detailed setup to configuration reference

---

kodiak/main.py
kodiak/pull_request.py
kodiak/queries.py
kodiak/test_main.py

We now reevaluate all dependent PRs when their base branch updates (sends push webhook event).
Also remove unnecessary `res_json=res.json()` tags in logging because we cover those with `add_request_info_processor`.
fixes #244

fix: PRs not reevaluating on base branch update

---

docs/README.md
docs/docs/config-reference.md
docs/docs/troubleshooting.md

- Update the documentation to mention that the config can be placed in .github/.kodiak.toml in addition to the repository root.
- Update the known issue documentation to mention that commit signatures only work for merge commits.
- fix a typo in the docs README.

doc: add info about .github/.kodiak.toml. update commit signing issue.

---

kodiak/main.py
kodiak/queries.py
kodiak/queue.py

When we receive a status webhook event we look at the commit information to determine which PRs are associated with this event.
Previously our API call to GitHub incorrectly used the `head` query param by passing a SHA when it wanted a "org_name:ref_name". This error meant that our API call was returning _all_ open PRs instead of just the ones that depended on the branch.
Now we only fetch all open PRs in case we cannot find references for the current commit. This covers the case of PRs opened from forks, which the status event doesn't provide an owner for to make a GitHub API query.

fix: bug with status event logic

---

docs/docs/config-reference.md
docs/static/css/custom.css

CHANGES
- break out config information into HTML. This will allow algolia to index our config options.
- update the CSS for the right sidebar to hide overflowing text with an ellipsis instead of allowing wrapping.
- update large configuration example with updating documentation.

add(docs): detailed information about configuration options

---

kodiak/evaluation.py
kodiak/test_evaluation.py
tox.ini

- add tests to cover pull requests in different states for `approve.auto_approve_usernames`
- add BaseMockFunc repr to make test failures more clear
- configure pytest to use ipdb for `--pdb`

fix: approve.auto_approve_usernames to only affect open, non-draft PRs

---

docs/siteConfig.js

With this url, docusaurus adds an Edit button to each doc page.
rel: https://docusaurus.io/docs/en/site-config.html#editurl-string

add(docs): edit url to enable edit button on doc pages

---

web_api/core/middleware.py
web_api/core/test_views.py
web_api/core/urls.py
web_api/core/views.py
web_api/tox.ini
web_api/web_api/settings.py

Update authentication flow to work with web ui. I want the app and the api to have different hosting, so we won't have NGINX to do proxying. This means we have to fight around CORs, so the authentication process is a little tricky (at least to me).
I have an urge to use token authentication, but this session stuff appears to work for now.

fix(web-api): authentication issues

---

web_ui/config/webpack.config.js
web_ui/package.json
web_ui/scripts/start.js
web_ui/yarn.lock

Create React App has an error message screen that pops up when
there is an error from typescript. Sometimes these are type errors, but
a lot of the time they're errors around dead code, unused variables, etc.
Instead we can run typescript in a terminal window or use vscode. Less
intrusive to development.
Also needed to fudge with the start script provided by create react app
so that it wouldn't hang at a message about waiting for type check
results.
Removed some other unnecessary webpack plugins.

tools(web_ui): remove compiler error screen from webpack config

---

docs/docs/recipes.md

The GitHub v3 API and the v4 api return difference results for the username of bots. The v3 API returns the name, appended with `[bot]`, like "kodiakhq[bot]", but the v4 api simply returns "kodiakhq". We were using the incorrect name for dependabot because we use the v4 API.
related: https://github.com/chdsbd/kodiak/issues/208#issuecomment-584639603

fix(docs): dependabot recipe to use correct username

---

web_api/core/auth.py
web_api/core/exceptions.py
web_api/core/middleware.py
web_api/web_api/settings.py
web_ui/src/world.ts

When a user is logged out or session expires they will get 401s from the API. This change makes it so when a user tries to access a page that requests one of these endpoints they will be redirect to login.

add(web): logic to redirect on auth failure

---

web_ui/netlify.toml

We need redirects to support React Router.
The API isn't running yet, but this configuration file should make the Netlify deploy work.
Now we have Netlify run for the docs and for the web app.

add(web_ui): netlify configuration for react app

---

bot/kodiak/event_handlers.py

When connecting to a Redis server using password authentication, `asyncio_redis` throws an exception when a GitHub webhook is received:
```
INFO uvicorn:httptools_impl.py:436 ('10.xx.xx.xx', 35906) - "POST /api/github/hook HTTP/1.1" 500
ERROR uvicorn:httptools_impl.py:371 Exception in ASGI application
Traceback (most recent call last):
File "/var/app/.venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/var/app/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
await super().__call__(scope, receive, send)
File "/var/app/.venv/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
await self.error_middleware(scope, receive, send) …
```

fix(bot): convert redis password to bytes when BytesEncoder is used

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/queries.py
bot/kodiak/test/fixtures/api/get_event/behind.json
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py
docs/docs/config-reference.md

Add option to add the pull request author as a trailer to the merge body using the `Co-authored-by: Jane Doe <j.doe@example.com>` format.
This change creates a workaround for #300.
The end result is not perfect, but I think it's the best we're going to be able to do for the moment.

add(bot): config merge.message.include_pull_request_author

---

web_ui/s/dev
web_ui/src/auth.ts
web_ui/src/components/OAuthPage.tsx
web_ui/src/world.ts

If a user attempts to access an authenticated page but is not logged in, they are redirected to the login page and are redirected to the root page upon successful authentication.
This change will result in the user being redirected to the page they attempted to access but were missing authentication. For example, if a user attempts to access https://app.kodiakhq.com/t/f8c69022-fcba-42a5-9e85-da3a466e6008/ without authentication, after they login successfully, the will be redirected back to that page!
CHANGES
- add login redirects
- update dev script to use new domain

add(web_ui): redirect for authed url

---

README.md
docs/pages/en/index.js
docs/siteConfig.js

Now that the dashboard is deployed at https://app.kodiakhq.com we should link to it!

add(docs): links to dashboard

---

web_ui/src/components/ActivityPage.tsx
web_ui/src/components/Page.tsx
web_ui/src/components/UsageBillingPage.tsx

Our mix of `h-100` on the containers and their parents results in scroll
bars on the loading states for the pages.
Some css changes to remove the scroll bars and center the loading spinner
in the center of the page.

fix(web_ui): page loading states having scroll bars

---

web_ui/src/components/ActivityChart.tsx

Our chart labels were being offset by one day because of how we were parsing the date strings. Parsing "2020-03-07" via `new Date()` gives us a date with an offset from UTC, effectively showing "2020-03-06". Using `parseISO` gives the correct behavior of giving the same "2020-03-07" in the current user's timezone.

fix(web_ui): chart label date offsets

---

web_ui/src/components/AccountsPage.tsx

The accounts links now have spacing between items and have even width.
before
after

fix(web_ui): accounts layout to have even spacing

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/queries.py
bot/kodiak/test/fixtures/api/get_event/behind.json
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py

When enabled, should make it easier to click back to the pull request
the commit came from.

add(bot): merge message option to include pull request URL

---

docs/docs/config-reference.md
docs/docs/recipes.md

`include_pull_request_author` was added to mitigate the fallout of GitHub's
change to how they process squashing of PRs. GitHub reverted that change
a couple days later so updating the docs to note how this option isn't
necessary anymore.

update(docs): include_pull_request_author w/ github revert info

---

bot/kodiak/test_config.py

Previously we didn't offer any tips to update the schema. Ideally we'd
have some sort of snapshot setup, but what we have works for the most
part.
Before we just said the schema shouldn't change on error, now we provide
the command to update the schema.
The error:
```
============================================== FAILURES ===============================================
_________________________________________ test_config_schema __________________________________________
def test_config_schema() -> None:
"""
Although we don't use the config schema anywhere, it provides a form of
documentation for the bot config.
"""
schema_path = load_config_fixture("config-schema.json")
>       assert json.loads(V1.schema_json()) == json.loads(
schema_path.read_text()
), (
"schema shouldn't change …
```

update(bot): config schema test failure message to be helpful

---

.kodiak.toml

GitHub fixed the issue with PR attribution a few days after releasing
the change so we no longer need this.

update(tools): remove `include_pull_request_author` flag from kodiak cfg

---

infrastructure/playbooks/dashboard-deploy.yml

We're running different Ubuntu versions for different environments, some
are using pip3, others pip.
Now we install both so deploy will hopefully "just work".

update(deploy): dashboard playbook to install both versions of pip

---

web_ui/nginx.conf

Without the proper header, browsers will use their heuristic caching
which means users might not get the latest version for a bit (depends on
how long the bowser decides to cache it).
rel: https://github.com/recipeyak/recipeyak/pull/561

add(dashboard): cache control header to disable caching for index.html

---

web_ui/Dockerfile
web_ui/general_headers.conf
web_ui/nginx.conf

`add_header` clears headers added in the parent so when we add the cache
specific header, we clear all the security headers
rel: http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
rel: https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx
rel: https://github.com/recipeyak/recipeyak/pull/562

fix(dashboard): nginx config to include missing headers

---

web_api/core/test_views.py
web_api/core/views.py

We didn't provide an order by clause when fetching accounts for the
accounts switcher so the order is not great.

fix(web_api): ordering of accounts endpoint

---

web_ui/src/api.ts
web_ui/src/world.ts

Currently using `object` which results in `any` and is too lenient for
what [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData#append()) supports.
We accept both string and number even though form data only allows
string and blob as values. Easier to convert the number than update
all the call sites.
We also have to convert some `interface`s to `type`s since `interfaces` don't have implicit index signatures: https://github.com/Microsoft/TypeScript/issues/15300

minor(web_ui): update jsonToFormData type to be more strict

---

web_api/core/test_views.py
web_api/core/views.py

The stripe invoice webhook handler was setting incorrect timestamps for subscription durations. Instead of relying on the invoice event, we call out to Stripe to get the current subscription.

fix(web): stripe invoice webhook handler to use correct period

---

.circleci/config.yml
bot/kodiak/cli.py
bot/kodiak/queue.py
bot/kodiak/refresh_pull_requests.py
web_api/core/models.py
web_api/core/test_account.py

When a user hits the paywall, they will need to start a trial or subscription to remove it. However, Kodiak only evaluates a PR when it gets a new related GitHub webhook. So after starting a trial or subscription the user would still see paywalls on their PRs unless they trigger a refresh by updating the PR.
This change adds a method for triggering the bot to reevaluate PRs outside of GitHub webhook triggers. This change adds a process that will listen for events in Redis and trigger updates in the bot.
On trial or subscription upgrades the web api will send a refresh message via Redis to the listening process. The listening process will enqueue webhook events for all open PRs into the webhook event queue, like a normal GitHub webhook event, triggering reevaluation of PRs.
I've done …

add: channel for triggering bot to reevaluate PRs

---

web_api/core/models.py
web_api/core/test_account.py

An account should hit the paywall if they have active users but don't have a trial or subscription.
Previously if a user didn't have a trial or subscription, they'd have full access.

fix(web_api): paywall for missing subscription and trial

---

bot/kodiak/evaluation.py
bot/kodiak/queries.py
bot/kodiak/test_evaluation.py

We were missing some check run states like `STALE` and `SKIPPED`. We also weren't marking `CANCELLED` check runs as failures, so Kodiak was erroneously waiting for them to succeed. This change makes Kodiak's behavior match GitHub.

fix(bot): handling of rare check run statuses

---

.circleci/config.yml

Having the branch name in the cache path isn't necessary since an
equivalent lock file should have equivalent dependencies.
This should make CI a bit faster.

update(tools): circle config to not cache based on branch

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

"💳 payment required: ..." => "💳 subscription: ..."
I think this is more accurate because payment isn't necessarily required for trials and complimentary access.

ref(bot): make paywall message less ominous

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py
web_api/core/test_account.py

If an account is missing subscription information in Redis, don't block access. Subscription blocking information will be set via the web_api.
This change is what we had originally. I think this is a bit nicer for new users because we don't need to immediately require them to start a trial or subscription. It also means we can elect to ignore hitting certain users with paywalls from the web_api side.

add: missing subscription in Redis should not block access

---

web_ui/src/components/UsageBillingPage.tsx

Previously we had the date with UTC appended when the date was actually
formatted with the browser's timezone.
Now we format the date with the timezone info to avoid any ambiguities.
rel: https://date-fns.org/v2.9.0/docs/format

fix(web_ui): billing trial expiration timezone

---

web_ui/src/components/UsageBillingPage.tsx

Previously the start subscription form defaulted to 1 seat. This is a bad default and has caused issues for some customers. We now default to the active user count.
We also change the "Select at least N seats to continue service." font color to red when the user has not selected enough seats.
**default state**
**too few seats**

fix(web_ui): start subscription form seat selection clarity

---

web_api/core/models.py
web_api/core/test_account.py
web_api/core/test_views.py
web_api/core/views.py
web_ui/src/api.ts
web_ui/src/components/UsageBillingPage.tsx

This change makes Kodiak free for personal GitHub accounts. Kodiak now only requires a subscription for private GitHub organization repositories.
The subscription section is replaced with some copy saying Kodiak is free for personal accounts.

add(web): make Kodiak free for personal accounts

---

docs/siteConfig.js

This nav link worked on the homepage, but it didn't work anywhere else.
I don't think we should bother making this a link to quickstart since "Docs" links to that already.

cut(docs): invalid nav link to #quickstart

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

fixes https://github.com/chdsbd/kodiak/issues/276
This problem is #276 is that the `merge.blacklist_title_regex` was taking priority over `merge.notify_on_conflict`. This is not as desirable because I think merge conflict notifications are higher priority.
I was going to make a more general change in #364, but I think this is a simple solution that addresses the immediate problem. I plan to circle back to #364 later.

add(bot): prioritize merge conflict notifications

---

web_api/core/models.py
web_api/core/test_user.py
web_api/core/test_views.py

If the user is a collaborator of an organization instead of a member or admin, calling GET https://api.github.com/orgs/:org/memberships/:user will fail with a permission error. This change handles that case.

fix(web_api): oauth flow not handling api error in membership check

---

bot/.isort.cfg
bot/.vscode/settings.json
kodiak.code-workspace
web_api/.isort.cfg
web_api/.vscode/settings.json

Previously opening the project in the root wouldn't work well with vscode.
Each subproject needed to be opened separately to get lints & friends to
work.
Workspace allows each subfolder config to work as expected.
Opening the project in vscode is now done via:
```
code kodiak.code-workspace
```
in the root of the project.
Also updated the isort config because redis was being treated as a first party module.
rel: https://code.visualstudio.com/docs/editor/multi-root-workspaces

update(tools): vscode cfg to sort imports & use project specific tools

---

bot/kodiak/evaluation.py
bot/kodiak/queries.py
bot/kodiak/test/fixtures/api/get_event/behind.json
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py
docs/docs/config-reference.md

We shouldn't bother doing this work if we don't need to.
I think when automatic branch deletion was first introduced by GitHub it didn't work for bots, but now it does, so making the requests to github is a waste of time.

ref(bot): skip branch deletion if branch deletion is enabled on repo

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

Post merge Kodiak said their was a merge conflict. This problem was introduced in #371, because prior to that we would return early if the PR was merged or closed, avoiding the merge conflict logic.
When a pull request is merged we will get `MergeStateStatus.DIRTY` and `MergeableState.CONFLICTING `, which would normally trigger a merge conflict error. However it's not helpful to leave a comment when the pull request is merged, so now we check and only comment if the pull request is open.

fix(bot): ignore conflicts when the PR is closed or merged

---

bot/kodiak/evaluation.py
bot/kodiak/queries.py
bot/kodiak/test/fixtures/api/get_event/behind.json
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py

If a push allowance was for a non-app actor we'd get:
```
{
"actor": {}
}
```
Instead of:
```
{
"actor": {
"databaseId": 29196
}
}
```
This would fail to parse, which would cause the BranchProtectionRule to return None and Kodiak to not run.

fix(bot): pushAllowance parsing for non-app actors

---

bot/kodiak/pull_request.py
bot/kodiak/test_pull_request.py

This change allows passing in an api client into PRV2. This change adds testing using this feature to allow us to test API failure behavior.
This is split off from https://github.com/chdsbd/kodiak/pull/394, because I wanted to separate the new testing logic from any behavior changes.

add(bot): testing for pull request querying

---

bot/kodiak/config.py
bot/kodiak/errors.py
bot/kodiak/evaluation.py
bot/kodiak/messages.py
bot/kodiak/pull_request.py
bot/kodiak/queries.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py

This change disables Kodiak merging a pull request when it encounters an internal server error from the GitHub merge api. In this event, Kodiak adds a label `disable_kodiak_label` and leaves a comment describing the issue. Kodiak will not update, approve, comment on, label, or merge a pull request with the `disable_kodiak_label`. It will still update status checks. The user must remove this label to re-enable Kodiak merging the pull request.
fixes #397
It is dangerous to retry merging when GitHub returns an internal server error (HTTP status code 500) because the merge can partially succeed in a way that will allow Kodiak to erroneously merge in a pull request multiple times, as we've seen in #397.
The GitHub pull request merge API is _not always_ idempotent …

fix(bot): disable Kodiak on GitHub API merge internal server error

---

docs/docs/troubleshooting.md

I neglected to add this documentation even though I linked to it in the pull request comment:
https://github.com/chdsbd/kodiak/blob/9d60ed69160fa16bec36a29d6aba1f150fb0961e/bot/kodiak/evaluation.py#L796-L798

add(doc): merge errors documentation

---

bot/kodiak/queue.py

Previously the last queue_name to be set was the one attached to the Sentry context. I believe this change should now make per-task Sentry contexts.
I found this change from https://github.com/getsentry/sentry-python/issues/147#issuecomment-432959196.
Not sure how to test this.

fix(bot): sentry context to work across tasks

---

bot/kodiak/queries.py

If a branch had a name that was not url safe, like `#123`, the resulting url we would call out to GitHub with would return 404 because `#` would leave the URL cut off.
The fix is to url encode the branch name. I've checked other queries and found one suspicious one and a false alarm.
If we pass url-unsafe parameters via `params` requests will escape them properly:
https://github.com/chdsbd/kodiak/blob/071ece2258de3eaa7dd34ec2db661d3c8ab3fc0b/bot/kodiak/queries.py#L902-L907
I think if a label was unsafely named we would fail to delete it. So I fixed this api call:
https://github.com/chdsbd/kodiak/blob/071ece2258de3eaa7dd34ec2db661d3c8ab3fc0b/bot/kodiak/queries.py#L1002-L1006
Fixes #407

fix(bot): escaping in delete branch and delete label api calls

---

bot/Dockerfile

Using `poetry run` means signals don't get sent correctly so stopping a container is slow. Calling uvicorn directly ensures signals are properly handled.
This is similar to what we do on the web api container.

fix: docker CMD to handle signals

---

bot/kodiak/pull_request.py

I have a suspicion that it's possible for an asyncio task to be stuck indefinitely. As a workaround we can set timeouts on certain areas to kill the task if it's taking too long.

add(bot): timeouts to event processing

---

bot/kodiak/evaluation.py

When the seats_exceeded subscription blocker was set and the user was an allowed user we would erroneously log a warning about an unexpected subscription status.

fix(bot): logging about unexpected blocker

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/pull_request.py
bot/kodiak/queries.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py

Add configuration option `merge.message.include_coauthors` to enable Kodiak to include coauthors in pull request body.
This option only applies to pull requests with `merge.message.body = "pull_request_body"`.
We add coauthors based on the last 100 commits on a pull request. We also only add coauthor information for commits that are linked to a GitHub user. We use the GitHub user's account information (login, id, name if available) to generate the coauthor trailers, not the commit author name or email.
resolves #277

add: merge.message.include_coauthors

---

web_ui/src/components/UsageBillingPage.tsx

We were using the $4.99 price even if the user had a different plan setup.

fix(web): show plan seat cost when modifying subscription

---

web_ui/src/components/UsageBillingPage.tsx

Previously we would fetch whenever the page loaded because the Modal component would load but remain hidden.

fix(web_ui): only fetch proration information when modal is visible

---

web_ui/src/components/Page.tsx

Previously you could only scroll on the center content and would get no feedback when scrolling in the margin.

fix(web_ui): scrolling to allow scrolling at margin of page

---

bot/kodiak/queries.py
bot/kodiak/test_queries.py

It appears that "user" can frequently be null. This is fine because we handle the errors, but we also log a warning which is noisy in Sentry.
We explicitly handle the null case so we don't log a warning about it.
This test doesn't really do much but I manually verified that we don't log a warning with this case.

fix(bot): error handling to be less noisy

---

docs/docs/recipes.md

dependabot-preview is going away and dependabot is the new name that most people will use.
fixes #445

update(docs): rename dependabot-preview to dependabot

---

docs/docs/recipes.md

The dependabot docs were kind of weak, so this PR adds more more information.

update(docs): add more examples to dependabot docs

---

docs/docs/config-reference.md
docs/docs/features.md
docs/docs/recipes.md
kodiak.code-workspace

Replace config options with there new alias.
I was planning to document each option, but realized that could be confusing. Instead we indicate the former names as aliases and add some notes.

update(docs): documentation for blacklist_ option removal

---

web_api/s/squawk.py

When merging to master CI runs again and the git command to fix Circle's
clobbering of the master ref fails.
Now we'll only run that when we aren't on master.
rel: https://github.com/recipeyak/recipeyak/pull/576

tools(squawk): fix setup for circle ci

---

bot/kodiak/event_handlers.py

Logging a warning automatically turns into a sentry issue.
We have a ton of errors around this message and they aren't actionable
so we can change it to an info level log and be done with it.

fix(sentry): remove logging for "could not find refs for status_event"

---

docs/docs/quickstart.md

Users should setup required status checks to prevent failing PRs from being merged.

update(docs): quick start information to mention required status checks

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test/fixtures/config/v1-default.toml
bot/kodiak/test_evaluation.py

If `merge.method` is not configured, use the first valid merge method in the repository based on the list "merge", "squash", "rebase".
For example, if a repository only allows "rebase" commits and `merge.method` is not provided, Kodiak will now use the "rebase" merge method. Previously it would have used the default "merge" method.
If a repository only allowed "squash" and "rebase", and `merge.method` was not configured, "squash" would be chosen because it is the first valid option in the list "merge", "squash", "rebase".
This change is backwards compatible for the most part. Kodiak now works instead of raising a configuration error if a user only allowed "squash" merge methods and didn't specify `merge.method`. If a user was relying on `"merge"` being the default, they will be okay since …

add(bot): use valid repo merge method if not specified

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

Previously we never update the status after merging a PR which means
the status stays at `status ⛴ attempting to merge PR (merging)`.
Now we show `merge complete 🎉`, but I'm open to other messages / emojis.
example of previous behavior: https://github.com/chdsbd/kodiak/runs/691144867
fixes: https://github.com/chdsbd/kodiak/issues/401

add(bot): setting success status on merge complete

---

web_api/s/squawk.py

Getting the migrations was bugged by using `..` instead of `...`.
Also there can be multiple migrations with the same id so we use the
full filename instead.
bump version as well
rel: https://github.com/recipeyak/recipeyak/pull/583

fix(CI): squawk python wrapper

---

bot/kodiak/pull_request.py

I think it was a mistake to not handle these timeout errors. If we hit a timeout Kodiak's basically dead until it receives another message for that pull request.
I think a better solution is to queue the pull request again on timeout. This way we won't loose the pull request and it won't block others because it will go at the end of the queue.
I'm also bumping the timeout because with our api rate limit we've been hitting a lot of timeouts recently.
FYI, we don't have any test coverage on this code.
_This pull request is best viewed with whitespace changes hidden_

update(bot): evaluation timeout to reduce errors

---

web_ui/.eslintrc.js

Probably not super necessary to add but might as avoid them if we can.
rel: https://steve.dignam.xyz/2020/07/24/pesky-globals/

tools(web_ui): add lints around restricted globals

---

docs/docs/config-reference.md

These links were broken ages ago when we created the web api and web ui.

fix(docs): broken links to code

---

docs/docs/config-reference.md
docs/docs/recipes.md

Speed and efficiency are kind of contradictory choices. This change breaks this recipe into two distinct options.
This change also adds slightly more detail to `merge.optimistic_updates`.
fixes #475

update(docs): split recipe and clarify merge.optimistic_updates

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

When mergeStateStatus is `UNKNOWN` we need to trigger a test commit so GitHub will evaluate the PR mergeability. This change fixes a conflict where the `merge.blocking_title_regex` was conflicting with the trigger_test_commit logic.
Now if a pull request state is `UNKOWN` we should always trigger a test commit.
Related https://github.com/chdsbd/kodiak/issues/261#issuecomment-671096403

fix(bot): merge blockers conflicting with test commits

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

When a pull request is merged the `mergeable` status becomes `UNKNOWN`. This meant we had an infinite loop where we'd trigger a test commit, queue the PR for another evaluation and continue to trigger test commits.
The fix is to only trigger test commits on open PRs.
Related #482

fix(bot): trigger test commit loop

---

bot/mypy.ini
web_api/mypy.ini

Now we explicitly ignore specific imports instead of a blanket ignore
on all missing types.
Upgraded databases and pytest to get their latest versions which include
types, for the rest we're ignoring them explicitly.
see https://github.com/chdsbd/kodiak/pull/485
- arrow
doesn't have types but we can replace it with std library calls
- requests_async
deprecated in favor of httpx, so we'd need to upgrade to get types.
The API of httpx is a little different as well.
- structlog
doesn't have types currently
https://github.com/hynek/structlog/issues/165
- rure
No stubs yet
https://github.com/davidblewett/rure-python/issues/23
- pytest_mock
types recently added to the typeshed so we'll need to wait for the next
release of mypy.
https://github.com/pytest-dev/pytest-mock/issues/152
- …

ref(mypy): don't ignore missing imports by default

---

web_ui/src/components/AccountsPage.tsx

When a user has zero accounts we now default the details panel to be open. This panel tells them to install Kodiak and to sync their accounts.

update(web_ui): open install dropdown when user has 0 accounts

---

.circleci/config.yml

The [circleci documentation](https://circleci.com/docs/2.0/configuration-reference/#filters-1) is not super clear, let's try this configuration. If the jobs doesn't get trigger anymore when change are made in a branch, we could add this additional snippet:
```
filters:
branches:
only: /.*/
tags:
only: /^v\d*\.\d*\.\d*$/
```
fix: https://github.com/chdsbd/kodiak/issues/493

tools(ci): trigger docker build on git tag creation

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

Allow users to override the `merge.method` setting in `.kodiak.toml` with a label (`kodiak:merge.method='rebase'`).
Something to be aware of is we have an existing label `kodiak:disabled` that we use to disable the bot in bad situations.
related #476

add(bot): merge method override with label

---

web_ui/src/components/UsageBillingPage.tsx

This field isn't required so we shouldn't mark it as such.

fix(web_ui): don't require Contact Emails

---

bot/kodiak/test_evaluation.py

This change supports a future PR that updates this test.

ref(bot): ignore draft PR test

---

bot/kodiak/test_evaluation.py

We created a more explicit way to write tests in #207 that results in fewer lines of code per test. This pull request removes all the remaining pytest fixture style tests.
depends on #510

ref(bot): finish refactoring old pytest fixture style tests

---

.circleci/config.yml

CircleCI sent an email warning users to authenticate Docker pulls (https://circleci.com/docs/2.0/private-images/) to bypass Docker's upcoming rate limits (https://docs.docker.com/docker-hub/download-rate-limit/).

update(ci): authenticate docker image pulls to bypass rate limits

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py

I think it will be less confusing for users if we have a single automerge label field instead of two.
`merge.automerge_labels` hasn't been released yet, so it's safe to remove. After seeing some ideas for using multiple labels with `merge.automerge_label` https://github.com/chdsbd/kodiak/issues/521#issue-718325968, I think it's better if we accept either a string or union of strings.
related #516

ref(bot): make merge.automerge_label accept arrays

---

docs/docs/troubleshooting.md

Kodiak now fully supports code owners as of https://github.com/chdsbd/kodiak/releases/tag/v0.30.0

docs(troubleshooting): remove codeowners caveat now that it is supported

---

docs/docs/self-hosting.md

When self hosting, Kodiak doesn't auto update so users need to be mindful
about bug fixes and changes related to GitHub API changes.
Easiest way is by watching the repo for new releases.

add(docs): self-hosting note about watching repo for releases

---

docs/docs/config-reference.md

The `update.autoupdate_label` configuration option added in #536 has been deployed so we can document this new option.

add(doc): update.autoupdate_label docs

---

bot/kodiak/test_evaluation.py

The diff here is atrocious, but previously we duplicated the `update.ignored_usernames` to cover `update.ignored_usernames` and the old name, `update.blacklist_usernames`. This change adds a for loop covering each case instead of duplicating the tests.

ref(bot): cut down on test duplication for update.ignored_usernames

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

When a pull request's author matches `update.ignored_usernames`, Kodiak will never update the pull request, unless `update.autoupdate_label` is applied to the pull request.
Previously Kodiak would still update the pull request just before merge. This caused merge conflicts with Dependabot workflows. Now Dependabot will handle updating the dependency pull requests.
related #537

update(bot): update.ignored_usernames should never update branch

---

docs/docs/config-reference.md

`update.ignored_usernames` was updated in #544 to prevent all updates, unless `update.autoupdate_label` is applied to a pull request. This change updates the docs to match this new behavior.

update(docs): document new `update.ignored_usernames` behavior

---

bot/kodiak/queries.py

Currently we only log the message and the response which doesn't give us
much to go off.
Instead we can use the logger with the repo name and org already bound.

ref(bot): log repo info w/ fail in fetch default branch name

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

Given the following Kodiak config,
```toml
merge.message.include_coauthors = true
merge.message.body = "empty"
```
before,
```
commit_message == ""
```
after,
```
commit_message == 'Co-authored-by: Barry Block <73213123+b-block@users.noreply.github.com>'
```
related: https://github.com/chdsbd/kodiak/issues/277#issuecomment-728304324

update(bot): support merge.message.include_coauthors empty merge bodies

---

.circleci/config.yml
bot/.isort.cfg
bot/README.md
bot/s/dev
bot/s/fmt
bot/s/lint
bot/s/test
web_api/README.md
web_api/s/dev
web_api/s/fmt
web_api/s/lint
web_api/s/test

`poetry run` is slow as it spawns a sub shell. Instead we can call the
executables directly from the venv which will achieve the same thing, but
quicker.

ref(dev): call python executables directly instead of through poetry

---

bot/.pylintrc
bot/kodiak/app_config.py
bot/kodiak/event_handlers.py
bot/kodiak/test_queries.py
bot/typings/asyncio_redis/connection.pyi
bot/typings/asyncio_redis/pool.pyi

Starlette types the config `__call__` method as returning `Any`. With a
few overloads we can get proper types for all the `cast`s

add(bot): types for config

---

bot/kodiak/queries.py

We introduced a bug that caused dates to be sent with an invalid format to GitHub. This meant check runs didn't work at all. This bad change hasn't been released, so we're okay.
https://github.com/chdsbd/kodiak/commit/c8de897eab3fb1c78516a504fa9f331021384a9a#diff-0958ca2d3d9da20b866adafe99f9e7c8169b99ba53d2a447b5e923a6d0dd3352L1074

fix(bot): check run date format

---

docs/docs/self-hosting.md

We had a misplaced "```", which was throwing off the formatting of the setup instructions.

fix(doc): formatting mistake in self-hosting docs

---

web_api/.pylintrc
web_api/mypy.ini
web_api/poetry.lock
web_api/pyproject.toml
web_api/web_api/auth.py
web_api/web_api/middleware.py
web_api/web_api/models.py
web_api/web_api/patches.py
web_api/web_api/settings.py
web_api/web_api/test_account.py
web_api/web_api/test_stripe_views.py
web_api/web_api/test_user.py
web_api/web_api/test_views.py
web_api/web_api/testutils.py
web_api/web_api/views.py

Add some basic django type stubs. There are some ignores around
`Request.user` since we don't inherit from `AbstractBaseUser`.
We're on an older version of Django that doesn't support indexing
into `QuerySet` or `BaseManager`, so we monkey patch those.

add(web_api): django type stubs

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py

If the commit message body is empty, don't add the two line spacing before coauthor trailers. GitHub adds it's own line between the title and body, so we'll have a three line space between the title and trailers if we don't remove our added spacing.
related #577

add(bot): limit coauthor trailer whitespace

---

bot/kodiak/evaluation.py
bot/kodiak/queries/__init__.py
bot/kodiak/queries/commits.py
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py

I think long term we should break up queries.py into multiple fields. I find it confusing having all the pydantic schemas in the same file.

ref(bot): move get_commit_authors into separate file

---

bot/kodiak/refresh_pull_requests.py

We weren't fetching the base refs for pull requests, so this service was failing when we tried to access the non-existent fields.

fix(bot): refresh pull requests ref handling

---

docs/docs/config-reference.md

When implementing this **awesome** tool 🙏, I observed that `automerge_label` accepts a `string` or `array`. 
I attempted to use  `automerge_labels`, which matches the docs but causes an error when Github Checks ran. 
> I believe the error was, **"automerge_label is not defined"**.
I continued to use my` automerge_label` **array** to fix the issue but changed the text from `automerge_labels` to `automerge_label`
Thanks for your great work!

fix: `automerge_labels` => `automerge_label`

---

.circleci/config.yml
docs/README.md
docs/package.json
docs/s/build
docs/s/dev
docs/s/fmt
docs/s/fmt-ci
docs/s/typecheck

This makes the `docs/` project consistent with `bot/`, `web_ui/`, and `web_api/` where we use `s/dev`, `s/lint`, etc., for our utility scripts.

ref(docs): use s/ folder instead of package.json

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py

`cut_body_before` was added via https://github.com/chdsbd/kodiak/pull/589
Add the second option, also handle the case where the match isn't found.
rel: https://github.com/chdsbd/kodiak/issues/550

add(bot): cut_body_after option for merge message

---

web_api/web_api/test_views.py

When this test was written, December 2020 was relatively far in the future. Now it's in the past and this test fails because December 5th, 2020 is more than 30 days ago.
I've updated the test to use the current date with offsets which should prevent flakiness in the future.

fix(web_api): flaky test with bad date

---

docs/docs/config-reference.md

Hey, we have noticed at my company that the documentation for `message.title` is slightly misleading. This aims to fix it. However I'm not sure if my wording is sufficient. Feel free to edit it. 🙏 
Funny how complex is such a thing as... commit message 😅

fix(docs): message.title follows with GitHub readme

---

web_api/poetry.lock
web_api/pyproject.toml

Latest version adds proper typing for `with connection.cursor() as cur:`
which we use in a few places for our aggregate queries.

deps(web_api): bump django-types to latest

---

bot/kodiak/config.py
bot/kodiak/dependencies.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_dependencies.py
bot/kodiak/tests/evaluation/test_automerge_dependencies.py

Add configuration option to auto merge PRs opened by Dependabot (and others) based on the upgrade type (major, minor, patch).
Snyk creates batch PRs, but Dependabot doesn't. I think for a first pass we can just support single dependency pull requests.
```toml
[merge]
automerge_label = "ship it!"
[merge.automerge_dependencies]
versions = ["minor","patch"]
usernames = ["dependabot"]
[update]
ignored_usernames = ["dependabot"]
```
related #606

add(bot): auto merge by dependabot version

---

docs/docs/config-reference.md
docs/docs/recipes.md

This change documents the newly released `merge.automerge_dependencies` configuration option.

add(docs): merge.automerge_dependencies recipe and config docs

---

docs/docs/config-reference.md

Kodiak can only merge pull requests that pass branch protection requirements.
related https://github.com/chdsbd/kodiak/pull/610#discussion_r567401413

add(docs): info about branch protection rules to docs

---

bot/.pylintrc
bot/kodiak/assertions.py
bot/kodiak/evaluation.py

`NoReturn` is Python's `never` which we can use to help ensure we handle
all cases.
I tried looking for other places where we could use this, but didn't
really find any easy places to add it.
Also we need to use `is` when comparing enum variants due to mypy's
backwards compatible refinement outlined in: https://github.com/python/mypy/issues/6366

ref(bot): use exhaustiveness checking via NoReturn type

---

bot/kodiak/queue.py
bot/typings/asyncio_redis/replies.pyi

With the recent changes to the merge queue display, the merging pull requests loses the time it was added to the queue and instead shows the time it started merging.
We can use the sorted set score to track the time the pull request was added to the merge queue and display that time when merging.

fix(bot): merge queue merging timestamp

---

docs/docs/permissions.md

We added the "Repository Workflows" permission to allow merging pull requests the modify workflow files.
related: #641

update(doc): permissions table to include repository workflows

---

CHANGELOG.md
bot/kodiak/event_handlers.py
bot/kodiak/events/check_run.py
bot/kodiak/test_events.py
bot/kodiak/tests/event_handlers/test_check_run.py

GitHub provides pull requests that are outside the current repository. I think this only affects public repositories, but it's a waste of resources to try to process these pull requests since we don't have access.

fix(bot): ignore external pull requests when enqueuing events

---

bot/kodiak/test_queries.py
bot/kodiak/tests/fixtures.py

fix(bot): skip redis-dependent test if Redis isn't running

---

docs/docs/config-reference.md

noticed a simple docs typo - sorry if annoying feel free to close!

docs: fix typo disabled require_automerge_label

---

bot/kodiak/evaluation.py
bot/kodiak/pull_request.py
bot/kodiak/queries/__init__.py
bot/kodiak/test_evaluation.py
bot/kodiak/test_pull_request.py
bot/kodiak/test_queries.py

This param is passed down into the evaluation logic, but isn't used.
We validate webhook signatures before putting them on the queue.
`git log -S` points to this param never being used.

cut(bot): unused param valid_signature

---

bot/kodiak/evaluation.py
bot/kodiak/pull_request.py
bot/kodiak/test_evaluation.py

This param was added in 4910a5c9dc176721dd504c7194595521df027ab8 but it
wasn't used, instead we accessed the info via `self.event.pull_request`

cut(bot): unused set_status param, latest_commit_sha

---

docs/docs/troubleshooting.md

Organizations need to know Kodiak's outgoing IP addresses for their IP allow list.

doc: outgoing IP addresses

---

CHANGELOG.md
bot/kodiak/queries/__init__.py

We recently (ae99de3ddaef1aca839c74c04c2fdb0fa8362858) replaced our old HTTP client, `requests_async`, with `httpx`. This gave us better testing support and allows us to specify an HTTP proxy for outgoing requests. One problem is `httpx` sets default timeouts that are different from `requests_async`.
`requests_async` has no default timeouts, which works for us because we set a [30 second](https://github.com/chdsbd/kodiak/blob/2111f3b07123ddd47c4157adf2d394984c259ae9/bot/kodiak/pull_request.py#L90) [timeout](https://github.com/chdsbd/kodiak/blob/2111f3b07123ddd47c4157adf2d394984c259ae9/bot/kodiak/pull_request.py#L119) for all PR evaluations by default. `httpx` uses a 5 second timeout for connect and read. We've been encountering frequent read timeouts since deploying …

fix(bot): remove http client timeout

---

bot/kodiak/events/status.py
bot/kodiak/test/fixtures/events/status/status_event.json

Apparently the sha of a commit can be nullable.

fix(bot): invalid event schema

---

bot/kodiak/queue.py
bot/kodiak/test_queue.py

Using queue names isn't a great way to match events to installation ids. By adding a new tag just for installation we can more easily lookup Sentry events by installation.

tool(bot): tag sentry events with installation id

---

bot/kodiak/pull_request.py
bot/kodiak/queries/__init__.py
bot/kodiak/queries/commits.py

We should only log errors or exceptions for behavior that requires developer intervention

update(bot): use warnings for normal errors

---

bot/kodiak/evaluation.py
bot/kodiak/test_evaluation.py
bot/kodiak/tests/evaluation/test_check_runs.py

Previously if a user created duplicate check suites with the same check run name, Kodiak would consider all of the check suites, not just the most recent one. So if the check suite had failed previously, but the latest check suite passed, Kodiak would incorrectly mark the PR as blocked for merging.
Now Kodiak only considers the most recent check run name.

fix(bot): handling of duplicate check suites

---

web_api/web_api/models.py
web_api/web_api/test_views.py
web_api/web_api/views.py

Previously if a user updated their payment method, their old payment method would still be attached to the subscription. This basically caused renewals to error until there was manual intervention.
Now, when a new payment method is attached, we remove the old ones so there is only ever one payment method attached to a customer.
We also use the first payment method available on an account for sending invoices when a user adds seats. Previously we would use the payment method attached to a subscription, but when we delete a user's initial payment method, that subscription.default_payment_method becomes null.

fix(web_api): billing payment method updates

---

bot/kodiak/dependencies.py

This is a minor refactor I pulled out of #713

ref(bot): use newer type annotations syntax

---

docs/docs/config-reference.md
docs/docs/recipes.md

I didn't want to duplicate every reference for Dependabot, so I sprinkled around a few mentions of Renovate.

feat(doc): mention renovate support

---

bot/kodiak/queries/__init__.py

This PR removes the call to `get_subscription` for self hosted instances. This was causing problems as the `get_subscription ` method instantiates a second Redis connection pool with a pool size defined by `USAGE_REPORTING_POOL_SIZE` (poor name choice given that it isn't only used when `USAGE_REPORTING is True`, but I suspect this is just a historical artefact). This second pool could quite easily push users over their hosted Redis connection limits, especially, as the undocumented `USAGE_REPORTING_POOL_SIZE` defaults to 50.
With this change the second pool is never instantiated if `USAGE_REPORTING is False && SUBSCRIPTIONS_ENABLED is False`. These are the default values for self hosted instances.

Only call `get_subscription` if required

---

bot/kodiak/queries/__init__.py

fix #721 
after debugging, I found that it is because the time drifting make github server think this request is making a too ambitious exp value.
the response is 
```
Expiration time\' claim (\'exp\') is too far in the future
```

less timedelta to prevent time drift

---

bot/poetry.lock
bot/pyproject.toml

..alongside its dependencies.
This change was introduced by invoking `poetry update uvicorn` after updating `pyproject.toml`.
Hoping that CI will cover more test setups than mine.

deps: update uvicorn to 0.15.0

---

bot/kodiak/evaluation.py
bot/kodiak/tests/evaluation/test_merge_message_trailers.py
docs/docs/config-reference.md

When enabling `include_pull_request_url` (defaults to false), prefix the URL added to the commit body with `PR-URL`. This follows other trailer syntax such as `Co-Authored-By:` as well as the general recommendations by [conventional commits][1] footer best practices.
Not sure how to handle with the fact that this could be seen as SEMVER breaking; changing expectations of commit body and all..
References: https://github.com/chdsbd/kodiak/issues/671#issuecomment-858240918
[1]: https://www.conventionalcommits.org/en/v1.0.0/

feat: prefix URLs with `PR-URL`

---

bot/kodiak/queries/__init__.py

Before this change, if an installation didn't have a .github repository, the GraphQL API request would error because we would provide a null value for the file expressions, when they're typed as non-null in the query.
Marking these arguments as nullable in the query resolves this issue.

fix(bot): owner/.github repos being null

---

bot/kodiak/queries/__init__.py

The `requiresConversationResolution` BranchProtectionRule isn't available until later GitHub Enterprise (GHE) versions, so we check the API before trying to use it.
I think in the future, if we use new fields we should update this logic to check for the field availability to ensure better GHE compatibility.
resolves #727
related #728

feat(bot): support older GraphQL schemas

---

bot/poetry.lock
bot/pyproject.toml

Our recent dependency upgrades moved us to a new version of httpcore that has been raising a NewConnectionRequired exception, breaking merging for some users.
I think this commit is the problem: https://github.com/encode/httpcore/commit/98fb2a0814d1fd076a354804f071cdcef9812615#diff-4f89d2e45c858632692840675cf189f73a499f51d39fc25c8f5bac828bd735e3R138
fixes #736

fix(bot): httpx instability by downgrading httpcore

---

bot/poetry.lock
bot/pyproject.toml

A later version of markdown-html-finder is needed to support Python 3.10.
Homebrew broke by Python installation, so I ended up installing 3.10 from python.org

ref(bot): support python 3.10

---

bot/kodiak/entrypoints/ingest.py
bot/kodiak/queue.py
bot/kodiak/redis_client.py
bot/kodiak/test_queries.py

close https://github.com/chdsbd/kodiak/issues/753

fix: remove .encode() from redis password

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/test_evaluation.py
bot/kodiak/tests/evaluation/test_check_runs.py
docs/docs/config-reference.md

- Add option to hide status message on PR's until  automerge label has been added, closes #747
(option defaults to `true`, so no breaking change)
- Make the missing automerge label message a little more friendly (see https://github.com/chdsbd/kodiak/issues/747#issuecomment-958260341)
- Add tests for new option and fix other tests
I've tested this via a self hosted Kodiak instance:
First scenario:
1. Create a PR (don't add automerge label)
2. Verify the correct message (`Ignored (no automerge label: ...`) is shown on PR
Second scenario:
1. Set `missing_automerge_label_message` to `false`
2. Create a PR (don't add automerge label)
3. Verify **no** message (`Ignored (no automerge label: ...`) is shown on PR
Third scenario (addressing …

Add option to hide status message when no automerge label

---

bot/kodiak/test_utils.py

I upgraded my local Python version to 3.8 and some of the tests were failing. Removing the future wrapping fixes the issue.

support Python 3.8 in tests

---

bot/kodiak/evaluation.py
bot/kodiak/tests/evaluation/test_branch_protection.py

A regression was introduced with #762 that caused the bot to attempt to update pull requests when changes were requested. This change fixes that issue.
related #761

fix(bot): don't attempt merge on changes requested

---

CHANGELOG.md
bot/kodiak/queries/__init__.py
bot/kodiak/test_evaluation.py
bot/kodiak/test_queries.py

This is enum is unused now since #762.

ref(bot): cut dead Permission enum

---

bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/tests/evaluation/test_merge_message_cut_body.py
docs/docs/config-reference.md

If `cut_body_after` or `cut_body_before` is in use, setting this option to `True` also strips the separator itself.
~Note, this is a draft; awaiting the following input:~
1. [x] Is there a better name? (renamed to `cut_body_and_text`)
2. [x] Should we improve the way the body string is managed?
3. [x] json schema generation is [having issues](https://github.com/chdsbd/kodiak/issues/770#issuecomment-998293493) with `REDISCLOUD_URL` and `SECRET_KEY`
Fixes: https://github.com/chdsbd/kodiak/issues/770

feat(bot): optionally strip the cut separator

---

docs/pages/en/index.js

Noticed we were missing the height and width for the image, so we were
getting some shifting.
The dimensions are chosen from what was being rendered.

fix(docs): add height & width to image to avoid layout shift

---

docs/README.md
docs/siteConfig.js

Algolia's removing their old indexing setup in three months, so we need to update our credentials to continue supporting indexing.
https://docsearch.algolia.com/docs/migrating-from-legacy/

update algolia to support new indexing scheme

---

CHANGELOG.md
bot/kodiak/config.py
bot/kodiak/evaluation.py
bot/kodiak/test/fixtures/config/config-schema.json
bot/kodiak/tests/evaluation/test_check_runs.py
docs/docs/config-reference.md

When `merge.block_on_neutral_required_check_runs` is enabled, we won't merge the pull request if a required check run has a neutral conclusion.
related: #780

feat(bot): merge.block_on_neutral_required_check_runs

---

docs/pages/en/index.js

The logo looked a little small with the default height

bump picpay logo height

---

docs/docs/recipes.md

I ran into a similar issue as #795 and added a slight tweak to the documentation that I think will clear the confusion for future readers.

Slight tweak to wording in "Automated dependency updates" recipe in docs

---

bot/kodiak/test_text.py
bot/kodiak/text.py

`markdown_html_finder` returns offsets in terms of bytes, but our Python code works in terms of unicode. `🏷️` is 11 characters, but 16 bytes. So if we have unicode in our PR body, stripping html characters doesn't work correctly.
The fix is to correctly handle byte offsets and unicode offsets. We must convert to bytes to accept the offsets from `markdown_html_finder`. But we must use unicode to parse HTML comments from those HTML snippets.
related #800

fix stripping html to correctly handle byte offsets

---

bot/kodiak/pull_request.py

If we get an error when making an API request, we generally return none.
If we're merging a PR, we should retry instead of returning early in this case.

retry when merging

---

web_api/mypy.ini
web_api/poetry.lock
web_api/pyproject.toml
web_api/web_api/auth.py
web_api/web_api/settings.py

Latest version of stripe type stubs are more filled out and provide some useful type checking:
https://github.com/python/typeshed/pull/7978

fix(web_api): add type stubs for stripe

---

bot/kodiak/queries/__init__.py
bot/kodiak/test/fixtures/api/get_event/behind.json
bot/kodiak/test_queries.py

We're getting an error where some of the `CheckRun`s returned by github
are `null`.
```
ValidationError
1 validation error for CheckRun
__root__
CheckRun expected dict not NoneType (type=type_error)
```

fix(bot): parsing of check runs related error

---

bot/kodiak/evaluation.py

We're getting sentry errors for whenever a PR is processed with an invalid config.
Kodiak gives a proper error message for this, so it's not important to report to sentry, so instead we can convert it to an info log.

ref(bot): change config related warning to an info log

---

bot/kodiak/queries/__init__.py
bot/kodiak/test/fixtures/api/get_event/no_latest_sha.json
bot/kodiak/test_queries.py

When a PR doesn't have any commits, we were failing to parse the response.
I think we could probably improve our mocking situation so its at the actual http response level rather than mocking the method, since the method gets called multiple times with different params.

fix(bot): error parsing response with no commits

---

bot/kodiak/cli.py
bot/kodiak/http.py
bot/kodiak/pull_request.py
bot/kodiak/queries/__init__.py
bot/kodiak/refresh_pull_requests.py
bot/kodiak/test_pull_request.py
bot/kodiak/test_queries.py
bot/kodiak/test_utils.py
bot/poetry.lock
bot/pyproject.toml
bot/tox.ini

Work around for a perf issue with how httpx handles SSL.
Instead of using `httpx.AsyncClient` directly, we subclass and reuse the ssl context.
rel: https://github.com/encode/httpx/issues/838

fix(bot): http client perf issue

---

bot/kodiak/test_evaluation.py
bot/kodiak/test_pull_request.py
bot/kodiak/test_queries.py
bot/kodiak/tests/evaluation/test_automerge_dependencies.py
bot/kodiak/tests/evaluation/test_branch_protection.py
bot/kodiak/tests/evaluation/test_check_runs.py
bot/kodiak/tests/evaluation/test_merge_message_trailers.py
bot/kodiak/tests/evaluation/test_merge_method.py
bot/kodiak/tests/test_fixtures.py
bot/mypy.ini
bot/poetry.lock
bot/pyproject.toml
bot/pytest_plugin/plugin.py
bot/tox.ini

Recently learned that the pytest-asyncio plugin can automatically handle the `pytest.mark.asyncio` stuff for us

ref(bot): cleanup asyncio test setup code

---

.circleci/config.yml
bot/Dockerfile
bot/supervisord.conf

While scanning the Kodiak Docker image with [Grype](https://github.com/anchore/grype), we noticed a significant amount of vulnerabilities.
This PR upgrade the base image to the latest 3.7 image and use the slim version which come with a smaller size and reduce the attack surface. I also took the opportunity to use a non root user.
- previously: image size 1.31GB, 3694 vulnerabilities
- now: image size 607Mb, 87 vulnerabilities

chore(bot): change Docker base image to python:3.7-slim

---

bot/pyproject.toml

Pytest was erroring because of this

Suppress syntax warning caused by rure in pytest
