- README.md
Outline why Kodiak exists.
How to use Kodiak.
How it works.
Deployment methods.
Updated development info.
> add documentation for usage to README

- poetry.lock
- pyproject.toml
fastapi was originally installed with all the extras. Most of these are unused.
> remove unused dependencies

- kodiak/evaluation.py
- kodiak/test_evaluation.py
We don't want to bother updating the branch if there are other failures.
> Update branch as late as possible

- kodiak/app_config.py
- kodiak/github/__init__.py
- kodiak/main.py
- kodiak/queries.py
- poetry.lock
- pyproject.toml
- pytest_plugin/plugin.py
Use Starlette's configuration feature to configure kodiak, redis, and
sentry. Configure sentry from the environment via SENTRY_DSN.
> Improve application configuration

- kodiak/main.py
> add emojis to status messages

- kodiak/queue.py
- poetry.lock
- pyproject.toml
CHANGES
- add position information to status messages
- update `zadd` calls to prevent updating existing items in sets
> ref(notifications): add position information

- kodiak/errors.py
- kodiak/evaluation.py
- kodiak/pull_request.py
- kodiak/queries.py
- kodiak/test_evaluation.py
Also define a base exception to inherit from instead of BaseException.
> ref: move Exceptions into own module

- kodiak/config_utils.py
- kodiak/pull_request.py
- kodiak/test_config.py
#116 was merged without addressing comments left on it. This change addresses those comments.
Fixes #121
> ref: address comments from #116

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/help-request.md
> add: issue templates

- .github/ISSUE_TEMPLATE/bug_report.md
> doc: address comments for PR templates

- kodiak/config.py
- kodiak/evaluation.py
- kodiak/github/__init__.py
- kodiak/github/events.py
- kodiak/github/test_webhook.py
- kodiak/pull_request.py
- kodiak/queries.py
- kodiak/test_pull_request.py
- kodiak/test_queries.py
This is an automated change to cleanup some cruft.
> ref: replace typing.NAME with NAME

- README.md
Here's a link to the fully rendered README for an example: https://github.com/chdsbd/kodiak/blob/simplify-readme/README.md
> doc: update README to be more streamlined

- kodiak/cli.py
- poetry.lock
- pyproject.toml
Add a cli for general util functionality and debugging purposes.
> add: cli for debug and util functions

- CHANGELOG.md
Update changelog in preparation for next release.
> release 0.6.0

- README.md
> doc: organization members permission requirement in README

- kodiak/conftest.py
- kodiak/pull_request.py
- kodiak/queue.py
- kodiak/test_pull_request.py
- kodiak/test_queue.py
We had some weird bugs where duplicate updates could be triggered.
> fix: update logic bailing early

- kodiak/errors.py
- kodiak/evaluation.py
- kodiak/pull_request.py
- kodiak/queue.py
- kodiak/test_evaluation.py
- kodiak/test_pull_request.py
> fix: skippable updates causing duplicate branch updates

- kodiak/config.py
- kodiak/queue.py
- kodiak/test/fixtures/config/config-schema.json
- kodiak/test/fixtures/config/v1-default.toml
- kodiak/test/fixtures/config/v1-opposite.1.toml
- kodiak/test/fixtures/config/v1-opposite.2.toml
- kodiak/test_config.py
Add configuration to bypass queue for PRs that are ready to merge.
Fixes #170
> add: merge.prioritize_ready_to_merge config

- CHANGELOG.md
- README.md
update changelog and document new configuration option
> release 0.9.0

- README.md
> doc: merge.block_on_reviews_requested bug

- README.md
https://github.com/Shopify/shipit-engine
> update(docs): add shipit to prior art

- README.md
Also change `Prior Art` to `Prior Art / Alternatives` since Ranger was
likely created after Kodiak.
> update(docs): add ranger to alternatives

- README.md
> fix(docs): link to alternative

- README.md
> doc: update Heroku setup to avoid key deserialization errors

- kodiak/pull_request.py
- kodiak/queue.py
When investigating https://github.com/chdsbd/kodiak/issues/189 we didn't
have enough logs to figure out what is going wrong.
Hopefully the next time Kodiak hangs, these logs will provide greater
insight.
> add: more logging for mergeability events

- kodiak/queries.py
- kodiak/throttle.py
logging in the throttling logic is too verbose to be useful.
> cut: noisy throttle logging

- README.md
Fork updates were fixed in #202
> remove old fork update warning from README

- .vscode/settings.json
I turned off the Microsoft Python language server because it was taking forever and warning about things like mypy Protocols being errors.
> tools: update vscode config

- kodiak/pull_request.py
- kodiak/queries.py
- kodiak/test/fixtures/api/get_event/behind.json
- kodiak/test_queries.py
Support placing .kodiak.toml in `.github/` folder.
fixes #223
closes #224
> add: support for .github/.kodiak.toml

- README.md
you guys should be more offensive regarding monetization for this wonderful project/product
> Added a 'Sponsoring' readme section

- docs/docs/sponsoring.md
- docs/sidebars.json
Copied the sponsorship info from the README into the docs.
rel: https://github.com/chdsbd/kodiak/pull/250
> add(docs): info on sponsoring

- docs/siteConfig.js
> fix(docs): open graph image links

- kodiak/evaluation.py
Configuration errors should be surfaced before Kodiak acts on a repository.
> ref: prioritize configuration errors in evaluation

- .circleci/config.yml
- web_api/core/event_ingestor.py
we should configure from environment!
> fix: redis config for event ingestor

- .kodiak.toml
Enable include_pull_request_author for this repository.
> add(tools): merge.message.include_pull_request_author

- web_api/core/models.py
Adding this constraint on the choices field helps ensure data integrity.
> add(web_ui): check constraint for AccountType choices

- docs/docs/config-reference.md
Add a description for the new merge message option.
> docs: merge.message.include_pull_request_url info

- web_ui/src/components/Page.tsx
- web_ui/src/components/SideBarNav.tsx
- web_ui/src/custom.scss
Simple stacking solution to move the nav to the top of the page when
on a mobile device.
Means we can actually use the site on a phone
> update(dashboard): sidebar to better support mobile devices

- .circleci/config.yml
- bot/s/build
- bot/s/dev
- bot/s/test
- infrastructure/kodiak_restart.sh
- s/shellcheck
- web_api/s/build
- web_api/s/test
- web_ui/s/build
- web_ui/s/fmt
- web_ui/s/lint
- web_ui/s/typecheck
- web_ui/src/components/ActivityChart.tsx
Our shell scripts have some issues, so let's make sure these issues
never occur again.
There is an existing shellcheck container on docker hub but it doesn't
have git, so using ubuntu.
> tools(CI): add shellcheck

- README.md
closes https://github.com/chdsbd/kodiak/issues/314
> Added complex-it sponsor

- web_api/Dockerfile
We were passing an invalid arg.
> fix(web_api): docker CMD args for gunicorn

- bot/kodiak/config.py
- bot/kodiak/evaluation.py
- bot/kodiak/test/fixtures/config/config-schema.json
- bot/kodiak/test_evaluation.py
- docs/docs/config-reference.md
- docs/docs/recipes.md
Hello @chdsbd thanks again for your great bot!, 
I've made an approach into the `update.username_blacklist` flag that we discussed on #326, since I'm new to Python (first code written ever, I'm a JS guy 😅) I may have made some mistakes so let me know what I should correct.
I renamed it to `blacklist_usernames` to share the same approach taken by `auto_approve_usernames` and `blacklist_labels` and also wrote a test covering the case (which looks to be passing).
My only issue is with schema, giving the following error:
```py
___________________________________________________________ test_config_schema ___________________________________________________________
def test_config_schema() -> None:
schema_path = load_config_fixture("config-schema.json")
>       assert …
```
> Implementing Auto Update Author Blacklist

- web_api/core/middleware.py
- web_api/core/test_middleware.py
- web_api/core/test_views.py
- web_api/web_api/settings.py
I copied these from recipeyak.
https://github.com/recipeyak/recipeyak/blob/514b372e91dce3756bd120fa0a54bf01a32a5e02/backend/backend/middleware.py#L115-L163
> add(web_api): /healthz and /readiness endpoints for uptime checking

- docs/docs/billing.md
- web_api/core/models.py
- web_api/core/test_views.py
- web_ui/src/components/UsageBillingPage.tsx
Kodiak is billed monthly and charges based on active users. I think it makes sense to give users a month to see how many active users they have.
> ref: 14 day trial to 30 day trial

- docs/docs/billing.md
We should only charge once for a given company.
> doc(billing): multiple organizations

- web_api/core/test_views.py
- web_api/core/views.py
- web_ui/src/api.ts
- web_ui/src/components/UsageBillingPage.tsx
This will help with another PR.
> ref(web): canSubscribe => accountCanSubscribe

- bot/kodiak/test_evaluation.py
We have a lot of unnecessary information in these evaluation.py tests. This change makes it so we only have information that's important to the test.
We're basically replacing all the pytest fixtures with plain functions.
I've changed one test as an example. I plan to make more changes in chunks via other PRs.
> ref(bot): simplify evaluation testing to be more readable

- bot/kodiak/test_evaluation.py
I think this is the halfway point.
> ref(bot): clean up evaluation tests part 4/?

- web_ui/.eslintrc.js
- web_ui/src/components/AccountsPage.tsx
- web_ui/src/components/SideBarNav.tsx
- web_ui/src/components/UsageBillingPage.tsx
- web_ui/src/useApi.ts
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md
https://github.com/typescript-eslint/typescript-eslint/blob/ee9f100a2f9a874c2b361482742686eeaa9bdac7/packages/eslint-plugin/docs/rules/consistent-type-assertions.md
> tools(web_ui): add missing eslint rules for typescript

- web_ui/src/components/UsageBillingPage.tsx
Co-authored-by: Steve Dignam <7340772+sbdchd@users.noreply.github.com>
> update(web_ui): copy for subscription benefits

- web_api/core/test_views.py
It seems this endpoint was neglected when we implemented billing. I'm planning to refactor this so we need a test to prevent regressions.
> add(web_api): test for fetch_proration endpoint

- docs/docs/config-reference.md
I want to keep this short, but I think this is an improvement.
fixes #446
> update(docs): clarify merge.optimistic_updates docs

- docs/docs/config-reference.md
Fixes https://github.com/chdsbd/kodiak/pull/449#pullrequestreview-434347940
> fix(docs): address PR feedback from #449

- bot/kodiak/test_evaluation.py
This change helps with a future PR that touches this same code. I wanted to add more test coverage.
related https://github.com/chdsbd/kodiak/issues/387
> ref(bot): test that default merge method is "merge"

- bot/kodiak/evaluation.py
- bot/kodiak/test_evaluation.py
This refactor will make a future PR smaller.
related https://github.com/chdsbd/kodiak/issues/387
> ref(bot): get_merge_body to make future change easier

- docs/docs/billing.md
The "Usage & Billing" page was redesigned and these docs weren't updated to reflect those changes.
> update(docs): billing docs to match new page layout

- docs/docs/recipes.md
fixes https://github.com/chdsbd/kodiak/issues/478
> fix(docs): invalid link to quickstart

- docs/docs/config-reference.md
> add(doc): merge.method config label documentation

- bot/poetry.lock
- bot/pyproject.toml
- web_api/pyproject.toml
I don't understanding what changed, but this seems to have worked.
> fix: ci build

- docs/docs/config-reference.md
Now that #522 has been deployed we should document this new feature.
> doc: merge.automerge_label array support

- web_api/web_api/models.py
- web_api/web_api/test_views.py
- web_api/web_api/views.py
This will help with future changes to the billing flow
> ref(web_api): centralize webhook handling logic

- docs/docs/config-reference.md
related https://github.com/chdsbd/kodiak/pull/504#discussion_r505391474
> fix(doc): merge.method config label quotes

- bot/kodiak/config.py
- bot/kodiak/evaluation.py
- bot/kodiak/test/fixtures/config/config-schema.json
- bot/kodiak/test_evaluation.py
> add(bot): update.autoupdate_label config option

- bot/kodiak/queries.py
- bot/kodiak/test_queries.py
The author of a review becomes null if the reviewer is a "ghost".
> fix(bot): null author for ghost reviewers

- docs/docs/self-hosting.md
> add(doc): GitHub Enterprise environment vars to self-hosting docs

- docs/docs/config-reference.md
> add(doc): `merge.priority_merge_label` config reference

- README.md
Fixing a small typo in readme :)
> fix(docs): fix a typo in readme

- docs/docs/config-reference.md
- docs/docs/features.md
Documentation for features added in #589 and #595.
> add(docs): docs for cut_body_before and cut_body_after options

- web_ui/.eslintrc.js
- web_ui/package.json
- web_ui/src/components/OAuthPage.tsx
- web_ui/src/components/SideBarNav.tsx
- web_ui/src/components/UsageBillingPage.tsx
- web_ui/yarn.lock
surfaced in https://github.com/chdsbd/kodiak/issues/624
see: https://github.com/yannickcr/eslint-plugin-react/blob/eeb92731bd922af4493cf938f0547a021e5cdbcf/docs/rules/jsx-no-useless-fragment.md
> add(web_ui): eslint for useless jsx fragments

- docs/docs/config-reference.md
> add(docs): rebase_fast_forward docs

- CHANGELOG.md
This release is mostly internal changes
> release 0.42.0

- web_ui/yarn.lock
I couldn't run the web ui until I upgraded node-sass to a newer version
> fix(web_ui): node-sass to use supported version

- docs/docs/troubleshooting.md
Kodiak needs repository access to run
Related #707
> add(doc): repositories access troubleshooting

- bot/kodiak/entrypoints/ingest.py
- bot/kodiak/logging.py
This is part of an effort to return the number of Sentry issues we report.
> log unknown events

- bot/kodiak/app_config.py
- bot/kodiak/entrypoints/ingest.py
- bot/kodiak/test_main.py
- bot/poetry.lock
- bot/pyproject.toml
We don't need FastAPI for our single API endpoint
> remove FastAPI and just use Starlette

- bot/Dockerfile
- bot/kodiak/queries/__init__.py
- web_api/Dockerfile
I've tested this on staging and in production. It works.
> add workaround for bug in GitHub GraphQL API

- bot/kodiak/evaluation.py
- bot/kodiak/queries/__init__.py
- bot/kodiak/test/fixtures/api/get_event/behind.json
- bot/kodiak/test/fixtures/api/get_event/no_author.json
- bot/kodiak/test/fixtures/api/get_event/no_latest_sha.json
- bot/kodiak/test_evaluation.py
I'll make another PR to block merge for this case once we log this for a bit.
> better support codeowner reviews

- bot/kodiak/redis_client.py
> Add support for specifing Redis username
